routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SubCategoryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VendorController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::middleware(['auth'])->group(function () {
    Route::resource('vendors', VendorController::class)->names('vendors');

    Route::resource('categories', CategoryController::class)->names('categories');

    Route::post('sub-categories', [SubCategoryController::class, 'store'])->name('subcategory.store');
    Route::get('sub-categories/{category?}', [SubCategoryController::class, 'create'])->name('subcategory.create');

    Route::resource('products', ProductController::class)->names('products');
    Route::resource('histories', HistoryController::class)->names('histories');
});

require __DIR__.'/auth.php';

app/Models/SubCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    use HasFactory;

    protected $table = 'sub_categories';

    protected $primaryKey   = 'uuid';
    protected $keyType      = 'string';

    public $incrementing    = false;

    protected $fillable     = ['uuid', 'code_sub_category', 'name_sub_category', 'category_uuid'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'created_at' => 'datetime:Y-m-d h:i:s',
        'updated_at' => 'datetime:Y-m-d h:i:s',
    ];

    /**
     * Get the Category that owns the SubCategory
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function Category()
    {
        return $this->belongsTo(Category::class, 'category_uuid');
    }
}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\SubCategory;
use Illuminate\Http\Request;
use Ramsey\Uuid\Uuid;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($category)
    {
        $category = Category::findOrFail($category);

        $data = [
            'category' => $category
        ];

        return view('subcategories.form', $data);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'category_uuid' => 'required',
            'code_sub_category' => 'required|unique:sub_categories,code_sub_category',
            'name_sub_category' => 'required'
        ]);

        $subcategory = SubCategory::create([
            'uuid' => Uuid::uuid4(),
            'code_sub_category' => $request->code_sub_category,
            'name_sub_category' => $request->name_sub_category,
            'category_uuid' => $request->category_uuid,
        ]);

        if ($subcategory) {
            return redirect("categories/$request->category_uuid")->with('info', 'Sub Kategori Berhasil ditambahkan!');
        } else {
            return redirect()->back()->with('danger', 'Sub Kategori Gagal Ditambahkan!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/subcategories/form.blade.php
@extends('layouts.admin')

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Form Sub Kategori</h1>
    {{-- <a href="{{ route('categories.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
        <i class="fas fa-plus fa-sm text-white-50"></i> Tambah Kategori
    </a> --}}
</div>

@include('layouts.components.alert')

<div class="card">
    <div class="card-body">
        {!! Form::open(['method' => 'post', 'url' => route('subcategory.store')]) !!}
            <div class="form-group">
                <label for="">Nama Kategori</label>
                {!! Form::text('category_name', $category->name_category, ['class'=>'form-control disabled','read-only' => true]) !!}
                {!! Form::hidden('category_uuid', $category->uuid, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                <label for="">Kode Sub Kategori</label>
                {!! Form::text('code_sub_category', null, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                <label for="">Nama Sub Kategori</label>
                {!! Form::text('name_sub_category', null, ['class'=>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::submit('Simpan', ['class' => 'btn btn-primary']) !!}
            </div>
        {!! Form::close() !!}
    </div>
</div>

@endsection

@push('js')

@endpush